get:
  tags:
    - Tasks
  summary: Show
  description: Get one task.
  operationId: Tasks_show
  security:
    - Bearer token: []
  parameters:
  - in: path
    name: id
    description: <u>[Task](/#operation/Tasks_list)</u> Id
    schema:
      type: integer
    required: true
  responses:
    '200':
      $ref: ../../components/responses/tasks/tasks_object.yaml
    '400': 
      $ref: ../../components/responses/errors/400.yaml       
    '401':
      $ref: ../../components/responses/errors/401.yaml 
    '500':
      $ref: ../../components/responses/errors/500.yaml    
post:
  tags:
    - Tasks
  summary: Update
  description: Update a task.
  operationId: Tasks_update
  security:
    - Bearer token: []
  requestBody:
    $ref: ../../components/requests/tasks/tasks_update.yaml
  parameters:
  - in: path
    name: id
    description: <u>[Task](/#operation/Tasks_list)</u> Id
    schema:
      type: integer
    required: true
  responses:
    '200':
      $ref: ../../components/responses/tasks/tasks_object.yaml
    '400': 
      $ref: ../../components/responses/errors/400.yaml       
    '401':
      $ref: ../../components/responses/errors/401.yaml 
    '500':
      $ref: ../../components/responses/errors/500.yaml    
delete:
  tags:
    - Tasks
  summary: Delete
  description: Delete a task.
  operationId: Tasks_delete
  security:
    - Bearer token: []
  parameters:
  - in: path
    name: id
    description: <u>[Task](/#operation/Tasks_list)</u> Id
    schema:
      type: integer
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            example:  
    '400': 
      $ref: ../../components/responses/errors/400.yaml       
    '401':
      $ref: ../../components/responses/errors/401.yaml 
    '500':
      $ref: ../../components/responses/errors/500.yaml    
