description: OK
content:
  application/json:
    schema:
      type: object
      properties:
        status:
          description: Status of response
          type: string
          example: "success"
        data:
          description: Response of the request
          type: array
          items:
            type: object
            properties:
              id:
                description: Opportunity custom field value Id
                type: integer
              title:
                description: Opportunity custom field value title
                type: string
          example: 
            - id: "5995"
              title: "Phone"
            - id: "5996"
              title: "Website"