openapi: 3.1.0
info:
  version: 1.0.0
  title: Karlia
  contact:
    email: contact@karlia.com
    url: 'https://karlia.fr'
  license:
    name: Apache 2.0 ou je sais pas
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'https://example.com/terms/'
  x-logo:
    url: 'https://karlia.fr/app/template/karlia/img/login/karlia-logo-1.PNG'
    altText: Logo Karlia
  description:
    $ref: ./info-description.md
tags:
  - name: Customers
    description: This section lists all the API related to the customers
servers:
  - url: 'https://karlia.fr/app/api/v2'
paths:
  # '/users/{username}':
  #   $ref: 'paths/users@{username}.yaml'
  /customers:
    $ref: paths/customers.yaml
components:
  securitySchemes:
    bearer_token:
      type: http
      scheme: bearer 
      bearerFormat: xxxxxx-xxxxxx-xxxx-xxxxxx-xxxxxx
