description: OK
content:
  application/json:
    schema:
      type: object
      properties:
        status:
          description: Status of response
          type: string
          example: "success"
        data:
          description: Response of the request
          type: array
          items:
            type: object
            properties:
              id:
                description: Supplier custom field value Id
                type: integer
              title:
                description: Supplier custom field value title
                type: string
          example: 
            - id: "5911"
              title: "30 days"
            - id": "5912"
              title: "45 days end of month"
          