get:
  tags:
    - Products
  summary: Custom fields
  description: Get a list of all products custom fields.
  operationId: Products_custom_fields_list
  security:
    - Bearer token: []
  responses:
    '200':
      $ref: ../../components/responses/products/products_custom_fields.yaml          
    '401':
      $ref: ../../components/responses/errors/401.yaml 
    '500':
      $ref: ../../components/responses/errors/500.yaml    