post:
  tags:
    - Products
  summary: Add/Update custom field
  description:  Add or update a product custom field.
  operationId: Products_custom_field_values_add_update
  security:
    - Bearer token: []
  parameters:
  - in: path
    name: id
    description: <u>[Product](/#operation/Products_list)</u> Id
    schema:
      type: integer
    required: true
  - in: path
    name: field_id
    description: Products <u>[custom field](/#operation/Products_custom_fields_list)</u> Id
    schema:
      type: integer
    required: true
  requestBody:
    $ref: ../../components/requests/products/products_custom_field.yaml
  responses:
    '200':
      $ref: ../../components/responses/products/products_object.yaml
    '400': 
      $ref: ../../components/responses/errors/400.yaml       
    '401':
      $ref: ../../components/responses/errors/401.yaml 
    '500':
      $ref: ../../components/responses/errors/500.yaml    