get:
  tags:
    - Products
  summary: VAT
  description: Get a list of all 'Value Added Tax'.
  operationId: Products_vat_list
  security:
    - Bearer token: []
  responses:
    '200':
      $ref: ../../components/responses/products/products_vat.yaml           
    '401':
      $ref: ../../components/responses/errors/401.yaml 
    '500':
      $ref: ../../components/responses/errors/500.yaml    