get:
  tags:
    - Products
  summary: Cost price
  description: Get the unit purchase cost of a product.
  operationId: Products_cost_price
  security:
    - Bearer token: []
  parameters:
  - in: path
    name: id
    description: <u>[Product](/#operation/Products_list)</u> Id
    schema:
      type: integer
    required: true
  - in: query
    name: quantity
    schema:
      type: number
      format: float
    description: Quantity
  responses:
    '200':
      $ref: ../../components/responses/products/products_cost_price.yaml       
    '400': 
      $ref: ../../components/responses/errors/400.yaml       
    '401':
      $ref: ../../components/responses/errors/401.yaml 
    '500':
      $ref: ../../components/responses/errors/500.yaml    