get:
  tags:
    - Products
  summary: Custom field values
  description: Get values of products custom field.
  operationId: Products_custom_field_values_list
  security:
    - Bearer token: []
  parameters:
  - in: path
    name: field_id
    description: Product <u>[custom field](/#operation/Products_custom_fields_list)</u> Id
    schema:
      type: integer
    required: true
  responses:
    '200':
      $ref: ../../components/responses/products/products_custom_field_values.yaml    
    '400': 
      $ref: ../../components/responses/errors/400.yaml       
    '401':
      $ref: ../../components/responses/errors/401.yaml 
    '500':
      $ref: ../../components/responses/errors/500.yaml    