description: OK
content:
  application/json:
    schema:
      type: object
      properties:
        status:
          description: Status of response
          type: string
          example: "success"
        data:
          description: Response of the request
          type: array
          items:
            type: object
            properties:
              id:
                description: Equipment custom field value Id
                type: integer
              title:
                description: Equipment custom field value title
                type: string
          example: 
            - id: "3671"
              title: "tag "
            - id": "6338"
              title: "tag1"
