description: OK
content:
  application/json:
    schema:
      type: object
      properties:
        status:
          description: Status of response
          type: string
          example: "success"
        data:
          description: Response of the request
          type: array
          items:
            type: object
            properties:
              id:
                description: Contact custom field value Id
                type: integer
              title:
                description: Contact custom field value title
                type: string
          example: 
            - id: "5991"
              title: "Commercial contact"
            - id: "5992"
              title: "Accounting contact"
            - id: "5993"
              title: "Decision-maker contact"
            - id: "5994"
              title: "Delivery contact"
