description: OK
content:
  application/json:
    schema:
      description: Response of the request
      type: object
      properties:
        id:
          description: Product category Id
          type: integer
          example: "510"
        title:
          description: Product category title
          type: string
          example: "Category #1"
        creation_date:
          description: Creation date and time
          type: string
          format: date-time
          example: "2022-04-13 12:09:06"
        created_by:
          description: Id of the creator
          type: integer
          example: "213"
        update_date:
          description: Update date and time
          type: string
          format: date-time
          example: "2022-04-13 12:09:13"
        updated_by: 
          description: Id of the updater
          type: integer
          example: "213"