description: OK
content:
  application/json:
    schema:
      type: object
      properties:
        status:
          description: Status of response
          type: string
          example: "success"
        data:
          description: Response of the request
          type: array
          items:
            type: object
            properties:
              id:
                description: Product custom field Id
                type: integer
                example: "3346"
              title:
                description: Product custom field title
                type: string
                example: "Conditioning"
              type:
                description: Customer custom field type
                type: string
                example: "Dropdown list"
              with_values:
                description: Custom field with values
                type: boolean
                example: "true"
              